#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

char *find_in_path(const char *file) {
    char *path = getenv("PATH");
    char *path_copy = strdup(path);
    if (!path_copy) return NULL;

    char *dir = strtok(path_copy, ":");
    char *result = NULL;
    while(dir) {
        char fullpath[1024];
        snprintf(fullpath, sizeof(fullpath), "%s/%s", dir, file);
        if (access(fullpath, F_OK) == 0) {
            if (access(fullpath, X_OK) == 0) {
                result = strdup(fullpath);
                break;
            }
            
        } else {
            errno = EACCES;
        }
        dir = strtok(NULL, ":");
    }

    free(path_copy);
    return result;
}

int main(int argc, char *argv[]) {
    extern char **environ;

    char **exec_argv = malloc((argc + 1) * sizeof(char *));
    exec_argv[0] = "strace";
    for (int i = 1; i < argc; i++) {
        exec_argv[i] = argv[i];
    }
    exec_argv[argc] = NULL;

    pid_t pid = fork();
    if (pid == -1){
        perror("fork");
        return 1;
    }

    if (pid == 0) {
        //printf("child\n");
        char *strace_path = find_in_path(exec_argv[0]);
        if (!strace_path) {
            fprintf(stderr, "找不到可执行文件: %s\n", exec_argv[0]);
            exit(1);
        }
        execve(strace_path, exec_argv, environ);

        perror("execve");
        free(strace_path);
        exit(1);
    }
    else {
        printf("father\n");
    }
    return 0;
}
