#include <unistd.h>
#include <sys/time.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

char *find_in_path(const char *file) {
    char *path = getenv("PATH");
    char *path_copy = strdup(path);
    if (!path_copy) return NULL;

    char *dir = strtok(path_copy, ":");
    char *result = NULL;
    while(dir) {
        char fullpath[1024];
        snprintf(fullpath, sizeof(fullpath), "%s/%s", dir, file);
        if (access(fullpath, F_OK) == 0) {
            if (access(fullpath, X_OK) == 0) {
                result = strdup(fullpath);
                break;
            }
            
        } else {
            errno = EACCES;
        }
        dir = strtok(NULL, ":");
    }

    free(path_copy);
    return result;
}

int main(int argc, char *argv[]) {
    // pipe
    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe");
        return 1;
    }
    char fd_path[32];
    snprintf(fd_path, sizeof(fd_path), "/dev/fd/%d", pipefd[1]);

    extern char **environ;
    int num_strace_cmd = 4;
    char **exec_argv = malloc((argc + num_strace_cmd) * sizeof(char *));
    exec_argv[0] = "strace";
    exec_argv[1] = "-T";
    exec_argv[2] = "-o";
    exec_argv[3] = fd_path;
    for (int i = 1; i < argc; i++) {
        exec_argv[i + num_strace_cmd - 1] = argv[i];
    }
    exec_argv[argc + num_strace_cmd - 1] = NULL;

    pid_t pid = fork();
    if (pid == -1){
        perror("fork");
        return 1;
    }
    if (pid == 0) {
        // this is child
        close(pipefd[0]);

        int devnull = open("/dev/null", O_WRONLY);
        dup2(devnull, STDOUT_FILENO);
        dup2(devnull, STDERR_FILENO);
        close(devnull);

        char *strace_path = find_in_path("strace");
        if (!strace_path) {
            fprintf(stderr, "找不到可执行文件: %s\n", "strace");
            exit(1);
        }
        execve(strace_path, exec_argv, environ);

        perror("execve");
        free(strace_path);
        exit(1);
    }
    // this is father
    else {
        close(pipefd[1]);

        char buf[BUFSIZ];
        char line_buf[BUFSIZ];
        size_t line_len = 0;
        ssize_t n;
        time_t last_print = 0;
        while ((n = read(pipefd[0], buf, BUFSIZ)) > 0) {
            for (ssize_t i = 0; i < n; i++) {
                if (buf[i] == '\n') {
                    line_buf[line_len] = '\0';
                    // 处理 line_buf
                    line_len = 0;
                }
                else if (line_len < sizeof(line_buf) - 1) {
                    line_buf[line_len++] = buf[i];
                }
                time_t now = time(NULL);
                if (now - last_print >= 0.1) {
                    // 打印信息
                    last_print = now;
                }
            }   
        }
        if (n < 0) {
            perror("read");
        }
    }
    close(pipefd[0]);
    return 0;
}
